apiVersion: v1
kind: Service
metadata:
  name: cat-svc
spec:
  selector:
    app: cat
  type: NodePort
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 8080
      nodePort: 31080
---
apiVersion: v1
kind: Service
metadata:
  name: monkey-svc
spec:
  selector:
    app: monkey
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dog-svc
spec:
  selector:
    app: dog
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 8080