apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-dp-gray
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: cat
      env: gray
  replicas: 1
  template:
    metadata:
      labels:
        app: cat
        env: gray
    spec:
      containers:
        - name: cat-ct-gray
          image: catface996/spring-cloud-istio-demo:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=cat --server.port=8080 --env=gray --next=true --service.url=http://monkey-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
          lifecycle:
            preStop:
              httpGet:
                host: dog-svc
                port: 80
                path: /sayHello
                schema: http
              



