apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-dp-life-cycle
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: cat
  replicas: 1
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
        - name: cat-ct
          image: catface996/spring-cloud-istio-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=cat --server.port=8080 --env=prod --next=true --service.url=http://dog-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
          securityContext:
            privileged: true 
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo $(date) 'written by postStart' >> /usr/local/log/out.log && sleep 2s"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "echo $(date) 'written by preStop' >> /usr/local/log/out.log && sleep 2s"]
          volumeMounts:
            - name: log-volume
              mountPath: /usr/local/log/
              readOnly: false
      volumes:
      - name: log-volume
        hostPath:
          path: /usr/local/log/
          type: DirectoryOrCreate
