apiVersion: apps/v1
kind: Deployment
metadata:
  name: biz-gateway-dp-prod
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: biz-gateway
      version: default
  replicas: 1
  template:
    metadata:
      labels:
        app: biz-gateway
        version: default
    spec:
      containers:
        - name: biz-gateway-ct-default
          image: catface996/spring-cloud-gateway-istio:lessee
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.cloud.gateway.routes[0].id=cat-svc --spring.cloud.gateway.routes[0].uri=http://cat-svc --spring.cloud.gateway.routes[0].predicates[0]=Path=/cat/{segment} --spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-dp-l1
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: cat
      version: L1
  replicas: 1
  template:
    metadata:
      labels:
        app: cat
        version: L1
    spec:
      containers:
        - name: cat-ct-l1
          image: catface996/spring-cloud-istio-demo:lessee
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=cat --server.port=8080 --env=L1 --next=true --service.url=http://dog-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-dp-l2
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: cat
      version: L2
  replicas: 1
  template:
    metadata:
      labels:
        app: cat
        version: L2
    spec:
      containers:
        - name: cat-ct-l2
          image: catface996/spring-cloud-istio-demo:lessee
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=cat --server.port=8080 --env=L2 --next=true --service.url=http://dog-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-dp-l3
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: cat
      version: L3
  replicas: 1
  template:
    metadata:
      labels:
        app: cat
        version: L3
    spec:
      containers:
        - name: cat-ct-l3
          image: catface996/spring-cloud-istio-demo:lessee
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=cat --server.port=8080 --env=L3 --next=true --service.url=http://dog-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-l1
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: dog
      version: L1
  replicas: 1
  template:
    metadata:
      labels:
        app: dog
        version: L1
    spec:
      containers:
        - name: dog-ct-l1
          image: catface996/spring-cloud-istio-demo:lessee
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=dog --server.port=8080 --env=L1 --next=false --service.url=http://xxx-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-default
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: dog
      version: default
  replicas: 1
  template:
    metadata:
      labels:
        app: dog
        version: default
    spec:
      containers:
        - name: dog-ct-default
          image: catface996/spring-cloud-istio-demo:lessee
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=dog --server.port=8080 --env=default --next=false --service.url=http://xxx-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"